// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using FormationHulk.Resources;
using FormationHulk.ViewControllers.iOS;
using FormationHulk.ViewModels;
using UIKit;

namespace FormationHulk.iOS
{
	public partial class MainViewController : BaseViewController<MainViewModel>
	{
		public MainViewController (IntPtr handle) : base (handle)
		{
        }

        protected override void SetupControls()
        {
            base.SetupControls();
			HelloWorld.Text = Strings.HelloWorld;
		}
	}
}
